# Generated by Django 5.0 on 2023-12-12 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sspscoresapp', '0002_score_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='variant',
            field=models.CharField(choices=[('SOLO', 'Solo'), ('FFA2P', 'Free-for-All Two-Player'), ('FFA3P', 'Free-for-All Three-Player'), ('FFA4P', 'Free-for-All Four-Player'), ('COOP2P', 'Cooperative Two-Player')], default='SOLO', max_length=6),
        ),
    ]
